server:
  port: 8888 # Définit le port sur lequel votre config-server sera disponible
spring:
  cloud:
  config:
  server:
  git:
  uri: https://gitlab.com/......................# Remplacez par l'URL de votre dépôt Git contenant
clone-on-start: true # Clone le dépôt Git lors du démarrage du serveur de configuration